### ISSUE TITLE
Cio engine

### ISSUE THREAD

**Issue by fjr619** [furqanullah717/Shopper-compose#1]
Why are you using cio for engine? Any spesific reason for that?

**Comment by fjr619** [comment]
On your ktor you are using cio, that what i mean. Any reason for using cio instead using other engine Android or Okhttp?

You can refer to this: https://ktor.io/docs/client-engines.html#platforms

**Comment by furqanullah717** [comment]
The primary reason for using the CIO engine is its compatibility with Multiplatform. Since I plan to eventually transition this project to a multiplatform framework, that's why I used CIO.
